---
services:
  skillgoblin:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./data/database:/app/data/database
      - ./data/content:/app/data/content
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
